### ISSUE TITLE
Panic on launch: "assertion failed: `(left == right)`"

### ISSUE THREAD

**Issue by nyanpasu64** [chiptunecafe/rawrscope#14]
When I try to run `cargo run --release`, a blank rawrscope windows, followed by a panic in the terminal:

```
  WARN@wgpu_core::instance  Missing features: VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS
  WARN@wgpu_core::instance  max_bind_groups limit is missing
  WARN@wgpu_core::device  Surface does not support present mode: IMMEDIATE, falling back to FIFO
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', <::std::macros::panic macros>:5:6
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:78
   3: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:59
   4: core::fmt::write
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libcore\fmt\mod.rs:1063
   5: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\io\mod.rs:1426
   6: std::sys_common::backtrace::_print
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:204
   9: std::panicking::default_hook
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:224
  10: panic_unwind::imp::exception_copy
  11: std::panicking::rust_panic_with_hook
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:474
  12: std::panicking::begin_panic_handler
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:332
  14: core::ptr::drop_in_place<core::result::Result<alloc::vec::Vec<u16>, std::io::error::Error>>
  15: core::ptr::drop_in_place<core::result::Result<alloc::vec::Vec<u16>, std::io::error::Error>>
  16: __mb_cur_max
  17: main
  18: panic_unwind::imp::exception_copy
  19: main
  20: invoke_main
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  21: __scrt_common_main_seh
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A dialog box opens up with the same information.

- Windows 10 x64 1909
- AMD Radeon(TM) RX Vega 10 Graphics
- rustc 1.43.0 (4fb7144ed 2020-04-20)

Running in the vscode CodeLLDB debugger implicates wgpu and DX12.

Specifically, this line in rawrscope crashes:

https://github.com/chiptunecafe/rawrscope/blob/b86f3f5344047ab778c05cdd76f47a4f4757316c/src/render.rs#L104-L114

And this line in wgpu:

https://github.com/gfx-rs/wgpu/blob/bc065e4abc24e82a2c92403740ffe8d7e6643243/wgpu-core/src/device/mod.rs#L1219

Which calls function https://github.com/gfx-rs/gfx/blob/fdfe887f5afab7ca057e3e824817d0bcdcf794ba/src/backend/dx12/src/device.rs#L2816 (but with no debug symbols)

I'll report an upstream bug soon.

**Comment by rastertail** [comment]
I have a feeling this is related to #8. Could you run without `--release` so there's a better backtrace? Even though it might be an upstream bug, since I can't reproduce it, it would be nice to see a better backtrace and get a better idea of what is going on.

**Comment by nyanpasu64** [comment]
```
  WARN@wgpu_core::instance  Missing features: VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS
  WARN@wgpu_core::instance  max_bind_groups limit is missing
  WARN@wgpu_core::device  Surface does not support present mode: IMMEDIATE, falling back to FIFO
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', <::std::macros::panic macros>:5:6
stack backtrace:

...trimmed

  13: std::panicking::begin_panic_fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:332
  14: gfx_backend_dx12::device::{{impl}}::write_descriptor_sets<alloc::vec::Vec<gfx_hal::pso::descriptor::DescriptorSetWrite<gfx_backend_dx12::Backend, core::iter::sources::Once<gfx_hal::pso::descriptor::Descriptor<gfx_backend_dx12::Backend>>>>,core::iter::sour
             at <::std::macros::panic macros>:5
  15: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_bind_group<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx12::Backend>
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.2\src\device\mod.rs:1206
  16: wgpu::Device::create_bind_group
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.0\src\lib.rs:736
  17: rawrscope::render::Renderer::new
             at .\src\render.rs:104
  18: rawrscope::commands::app::_run
             at .\src\commands\app.rs:176
  19: rawrscope::commands::app::run
             at .\src\commands\app.rs:466
  20: rawrscope::main
             at .\src\main.rs:38
```

time to https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html to find out just which assert is at fault

this kind of message showed up on the [gfx.rs/webgpu gitter](https://gitter.im/gfx-rs/webgpu?at=5d7e64a25d40aa0d7d3f87a6) last year, but no real bug report was filed.

**Comment by nyanpasu64** [comment]
>clone gfx (contains gfx-backend-dx12)
>no tags, don't know which revision to checkout
>get trait mismatch errors because gfx-backend-dx12 uses local `gfx`, but wgpu uses Cargo `gfx`
>instead use `gfx-backend-dx12-0.5.0` from ~/.cargo
>add `[patch.crates-io]`
>edit dx12 crate
>no rebuild, no changes, nothing happens
>delete dependencies, delete partial artifacts, trigger full rebuild by accident
>nothing happens
>realize I was editing the Git repo, not `gfx-backend-dx12-0.5.0`

By labelling each `assert_eq!()` with a string, I found that the following line is failing:

https://github.com/gfx-rs/gfx/blob/fdfe887f5afab7ca057e3e824817d0bcdcf794ba/src/backend/dx12/src/device.rs#L2894-L2895

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: SRV size % 4 != 0', <::std::macros::panic macros>:5:6
```

Filed at https://github.com/gfx-rs/gfx/issues/3235 .

**Comment by rastertail** [comment]
Honestly I wouldn't be surprised if this was an issue with my code in the end; a lot of the rendering code was poorly rushed together and I plan to rewrite some of it soon. Thanks for filing the issue on the gfx repo though, maybe they can help us out.

**Comment by rastertail** [comment]
Just pushed a commit that *might* fix this. Do you mind testing it?

**Comment by nyanpasu64** [comment]
Seems to work now, I don't understand your graphics code though. Is the assertion error caused by an incorrect unsafe impl on your part? Should gfx-rs change their logic or error handling?

**Comment by rastertail** [comment]
I think there's definitely value in keeping the issue open on the gfx repo just so that we can get better assert messages, but my issue here is that the docs are kinda unclear on what is and isn't allowed. In this case, I was *really* lazily handling the scenario of the line storage buffer being empty by just creating a buffer with a single zero byte in it, but the DX12 backend seems to want the buffer lengths to be multiples of 4 bytes.
